export const APPLY_VOLUNTEER_REQUEST = 'APPLY_VOLUNTEER_REQUEST'
export const APPLY_VOLUNTEER_SUCCESS = 'APPLY_VOLUNTEER_SUCCESS'
export const APPLY_VOLUNTEER_FAIL = 'APPLY_VOLUNTEER_FAIL'
export const APPLY_VOLUNTEER_RESET = 'APPLY_VOLUNTEER_RESET'

export const FETCH_VOLUNTEER_STATUS_REQUEST = 'FETCH_VOLUNTEER_STATUS_REQUEST'
export const FETCH_VOLUNTEER_STATUS_SUCCESS = 'FETCH_VOLUNTEER_STATUS_SUCCESS'
export const FETCH_VOLUNTEER_STATUS_FAIL = 'FETCH_VOLUNTEER_STATUS_FAIL'
